language: python

dist: xenial

sudo: true

python:
  - '3.4'
  - '3.5'
  - '3.6'
  - '3.7'

# commands to install dependencies
install:
  - "pip install flake8 pytest-cov pytest coveralls"
  - "pip install -r requirements.txt"

# commands to run tests
script:
  - "flake8 checkdmarc.py"
  - "flake8 tests.py"
  - "cd docs"
  - "make html"
  - "cd .."
  - "python tests.py"
  - "python setup.py sdist"
  - "python setup.py bdist_wheel"
